version: "3.9"

services:
  # ğŸŸ£ Base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: ordermanager_db
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ğŸŸ¢ Backend NestJS (modo desarrollo)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ordermanager_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "
        npx prisma generate &&
        npm run start:dev
      "

volumes:
  postgres_data:
